// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dygadnfeoiimmbeqbsvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Z2FkbmZlb2lpbW1iZXFic3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTUzMDcsImV4cCI6MjA5MzM5MTMwN30.KM9rgVqCPGRZlEAk-b8zeviHt2Z7JR7ZPE2wPJudxcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});